# Use container-based infrastructure
# Shamelessly stolen from http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
#sudo: false

language: scala

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

# This is an sbt plugin, so this section is for demo purpose
#scala:
   #- 2.12.1

jdk:
  - oraclejdk8
